# This is a basic workflow to help you get started with Actions

name: Vulnerability check for 2021.01-LTS

on:
  # Run every week on Sunday
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependencyVulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: implydata/druid
          ref: release/2021.01
          fetch-depth: 0
          token: ${{ secrets.PAT_FOR_GITHUB_ACTION}}

      - name: Run dependency check
        run: |
          mvn -B dependency-check:check || { echo "
          
          The OWASP dependency check has found security vulnerabilities. Please use a newer version
          of the dependency that does not have vulnerabilities. If the analysis has false positives,
          they can be suppressed by adding entries to owasp-dependency-check-suppressions.xml (for more
          information, see https://jeremylong.github.io/DependencyCheck/general/suppression.html).

          " && false; }
      - name: Slack Notification for job failed
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_MESSAGE: "There is a vulnerability in the 2021.01-LTS branch file a jira to fix this issue. Can github actions create this JIRA?"
          SLACK_TITLE: "[FAILED] Found vulnerability in dependencies for release/2021.01"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
