# This is a basic workflow to help you get started with Actions

name: Vulnerability check for 2021.01-LTS

on:
  # Run every week on Sunday
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependencyVulnerabilities:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 0.19.0-iap
          - 0.18.0-iap
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: mvn install
        run:  export MAVEN_OPTS="-Xms4g -Xmx8g -XX:MaxDirectMemorySize=2048m" && mvn -B clean install -q -ff -Danimal.sniffer.skip=true -Dcheckstyle.skip=true -Ddruid.console.skip=true -Denforcer.skip=true -Dforbiddenapis.skip=true -Dmaven.javadoc.skip=true -Dpmd.skip=true -Dspotbugs.skip=true -DskipTests -Djacoco.skip=true -T 1C
      - name: Run dependency check
        run: |
          mvn -B dependency-check:check || { echo "
          
          The OWASP dependency check has found security vulnerabilities. Please use a newer version
          of the dependency that does not have vulnerabilities. If the analysis has false positives,
          they can be suppressed by adding entries to owasp-dependency-check-suppressions.xml (for more
          information, see https://jeremylong.github.io/DependencyCheck/general/suppression.html).

          " && false; }
      - name: Slack Notification for job failed
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_MESSAGE: "There is a ${{ matrix.branch }} vulnerability in the 2021.01-LTS branch file a jira to fix this issue. Can github actions create this JIRA?"
          SLACK_TITLE: "[FAILED] ${{ matrix.branch }}Found vulnerability in dependencies for release/2021.01"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
